version: 2.1

### It's a good practice to keep your commands at the top of the config file. In this project, you'll need at least 2 commands:

# commands:
#   destroy-environment:
#     description: Destroy backend and frontend cloudformation stacks given a workflow ID.
#     ...

#   revert-migration:
#     description: Revert the last migration if successfully run in the current workflow.
#     ...
executors:
  node:
    docker:
      - image: circleci/node:14.17.4
  aws:
    docker:
      - image: amazon/aws-cli
  python:
    docker:
      - image: python:3.9.0-alpine

jobs:
  install-frontend-dependencies:
    executor: node
    steps:
      - checkout
      - run:
          name: npm install
          working_directory: ./frontend
          command: npm install
      - save_cache:
          paths:
            - ~/node_modules
          key: frontend-dependencies-{{ checksum "node_modules" }}

  build-frontend:
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: frontend-deps-{{ checksum "node_modules" }}
      - run:
          name: npm run build
          working_directory: ./frontend
          command: npm run build

#  test-frontend:

#  est-backend:

#  scan-frontend:

#  scan-backend:

#  deploy-infrastructure:

#  configure-infrastructure:

#  run-migrations:

#  deploy-frontend:

#  deploy-backend:

#  smoke-test:

#  cloudfront-update:

workflows:
  default:
    jobs:
      - install-frontend-dependencies

      - build-frontend:
          requires:
            - install-frontend-dependencies